# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: leaf++ blog
subtitle: 
subtitle_desc: 
slogan: 
keywords: 前端开发
description: 
author: leaf
language: zh-cn
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://leaf930814.github.io/
root: /
permalink: notes/:year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: notes
category_dir: cates
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - 'baidu*.html'
  - 'demo/**'

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: true
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# generator-index
index_generator:
  per_page: 24
  order_by: -date

# tag generator
## https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 24

# fragments generator
## https://github.com/mamboer/hexo-generator-fragments
fragments_generator:
  dir: fragments
  per_page: 24
  index_dir: index

# Pagination
## Set per_page to 0 to disable pagination
per_page: 24
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: lattice


# Feeds
## https://www.npmjs.com/package/hexo-generator-xfeed
xfeed:
  type: atom
  path: atom.xml
  limit: false

# Json Feeds
## https://github.com/alexbruno/hexo-generator-json-feed
jsonFeed:
  limit: 30

#stylus
stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .


# lunr
lunr:
  field: all
  path: assets/lunr/

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  message: Super BlockMan at {{ now('YYYY-MM-DD HH:mm:ss') }}
  repo: 
    github: git@github.com:leaf930814/leaf930814.github.io.git,master

# Disqus
disqus_shortname:

# Analytics
baidu_analytics: 
google_analytics:
ta_analytics: 53685723

# Social
twitter: leaf930814
github:
  user: leaf930814
  repo: leaf930814.github.io

# baidu sitemap
baidusitemap:
  url: 

baiduce: 

# filter_cleanup
hfc_useref:
  enable: true
  concat: true

hfc_html:
  enable: true

hfc_css:
  enable: true
  exclude: 
    - '*.min.css'

hfc_js:
  enable: true
  mangle: true
  exclude: 
    - '*.min.js'

hfc_img:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false

hfc_favicons:
  enable: false
  src: img/logo.png
  target: img/
  icons:
    android: true
    appleIcon: true
    appleStartup: false
    coast: false
    favicons: true
    firefox: false
    opengraph: false
    windows: true
    yandex: false

# O2 Theme Customation
logo_url: img/felogo.png

wechat:
  jssdk_url: 
